// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using senai.hroads.webApi.Contexts;

namespace senai.hroads.webApi.Migrations
{
    [DbContext(typeof(HroadsContext))]
    partial class HroadsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("senai.hroads.webApi.Domains.Classe", b =>
                {
                    b.Property<int>("idClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClassesHabilidadeidClasseHabilidade")
                        .HasColumnType("int");

                    b.Property<string>("nomeClasse")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("Nome");

                    b.HasKey("idClasse");

                    b.HasIndex("ClassesHabilidadeidClasseHabilidade");

                    b.HasIndex("nomeClasse")
                        .IsUnique();

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            idClasse = 1,
                            nomeClasse = "Bárbaro"
                        },
                        new
                        {
                            idClasse = 2,
                            nomeClasse = "Cruzado"
                        },
                        new
                        {
                            idClasse = 3,
                            nomeClasse = "Caçadora"
                        },
                        new
                        {
                            idClasse = 4,
                            nomeClasse = "Monge"
                        },
                        new
                        {
                            idClasse = 5,
                            nomeClasse = "Necromante"
                        },
                        new
                        {
                            idClasse = 6,
                            nomeClasse = "Feiticeiro"
                        },
                        new
                        {
                            idClasse = 7,
                            nomeClasse = "Arcanista"
                        });
                });

            modelBuilder.Entity("senai.hroads.webApi.Domains.ClassesHabilidade", b =>
                {
                    b.Property<int>("idClasseHabilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("idClasse")
                        .HasColumnType("int");

                    b.Property<int>("idHabilidade")
                        .HasColumnType("int");

                    b.HasKey("idClasseHabilidade");

                    b.HasIndex("idClasse");

                    b.HasIndex("idHabilidade");

                    b.ToTable("ClassesHabilidade");

                    b.HasData(
                        new
                        {
                            idClasseHabilidade = 1,
                            idClasse = 1,
                            idHabilidade = 1
                        },
                        new
                        {
                            idClasseHabilidade = 2,
                            idClasse = 1,
                            idHabilidade = 2
                        },
                        new
                        {
                            idClasseHabilidade = 3,
                            idClasse = 2,
                            idHabilidade = 2
                        },
                        new
                        {
                            idClasseHabilidade = 4,
                            idClasse = 3,
                            idHabilidade = 1
                        },
                        new
                        {
                            idClasseHabilidade = 5,
                            idClasse = 4,
                            idHabilidade = 3
                        },
                        new
                        {
                            idClasseHabilidade = 6,
                            idClasse = 4,
                            idHabilidade = 2
                        },
                        new
                        {
                            idClasseHabilidade = 8,
                            idClasse = 6,
                            idHabilidade = 3
                        });
                });

            modelBuilder.Entity("senai.hroads.webApi.Domains.Habilidade", b =>
                {
                    b.Property<int>("idHabilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClassesHabilidadeidClasseHabilidade")
                        .HasColumnType("int");

                    b.Property<int>("idTipoHabilidade")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idHabilidade");

                    b.HasIndex("ClassesHabilidadeidClasseHabilidade");

                    b.HasIndex("idTipoHabilidade");

                    b.ToTable("Habilidades");

                    b.HasData(
                        new
                        {
                            idHabilidade = 1,
                            idTipoHabilidade = 1,
                            nome = "Lança Mortal"
                        },
                        new
                        {
                            idHabilidade = 2,
                            idTipoHabilidade = 2,
                            nome = "Escudo Supremo"
                        },
                        new
                        {
                            idHabilidade = 3,
                            idTipoHabilidade = 3,
                            nome = "Recuperar Vida"
                        });
                });

            modelBuilder.Entity("senai.hroads.webApi.Domains.Personagem", b =>
                {
                    b.Property<int>("idPersonagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxMana")
                        .HasColumnType("int");

                    b.Property<int>("MaxVida")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataAtualização")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("DATE");

                    b.Property<int>("idClasse")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("idPersonagem");

                    b.HasIndex("idClasse");

                    b.HasIndex("idUsuario");

                    b.HasIndex("nome")
                        .IsUnique();

                    b.ToTable("Personagens");

                    b.HasData(
                        new
                        {
                            idPersonagem = 1,
                            MaxMana = 80,
                            MaxVida = 100,
                            dataAtualização = new DateTime(2021, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dataCriacao = new DateTime(2019, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idClasse = 1,
                            idUsuario = 2,
                            nome = "DeuBug"
                        },
                        new
                        {
                            idPersonagem = 2,
                            MaxMana = 100,
                            MaxVida = 70,
                            dataAtualização = new DateTime(2021, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dataCriacao = new DateTime(2016, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idClasse = 4,
                            idUsuario = 2,
                            nome = "BitBug"
                        },
                        new
                        {
                            idPersonagem = 3,
                            MaxMana = 60,
                            MaxVida = 75,
                            dataAtualização = new DateTime(2021, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dataCriacao = new DateTime(2018, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idClasse = 7,
                            idUsuario = 2,
                            nome = "Fer8"
                        });
                });

            modelBuilder.Entity("senai.hroads.webApi.Domains.TipoHabilidadeDomain", b =>
                {
                    b.Property<int>("idTipoHabilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.HasKey("idTipoHabilidade");

                    b.ToTable("TiposHabilidade");

                    b.HasData(
                        new
                        {
                            idTipoHabilidade = 1,
                            titulo = "Ataque"
                        },
                        new
                        {
                            idTipoHabilidade = 2,
                            titulo = "Defesa"
                        },
                        new
                        {
                            idTipoHabilidade = 3,
                            titulo = "Cura"
                        },
                        new
                        {
                            idTipoHabilidade = 4,
                            titulo = "Magia"
                        });
                });

            modelBuilder.Entity("senai.hroads.webApi.Domains.TiposUsuario", b =>
                {
                    b.Property<int>("idTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idTipoUsuario");

                    b.ToTable("TiposUsuario");

                    b.HasData(
                        new
                        {
                            idTipoUsuario = 1,
                            titulo = "administrador"
                        },
                        new
                        {
                            idTipoUsuario = 2,
                            titulo = "jogador"
                        });
                });

            modelBuilder.Entity("senai.hroads.webApi.Domains.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<int>("idTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("sobrenome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idUsuario");

                    b.HasIndex("idTipoUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            idUsuario = 1,
                            email = "admin@admin.com",
                            idTipoUsuario = 1,
                            nome = "Admin",
                            senha = "admin",
                            sobrenome = "adm"
                        },
                        new
                        {
                            idUsuario = 2,
                            email = "jogador@gmail.com",
                            idTipoUsuario = 2,
                            nome = "Jogador",
                            senha = "jogador",
                            sobrenome = "2"
                        });
                });

            modelBuilder.Entity("senai.hroads.webApi.Domains.Classe", b =>
                {
                    b.HasOne("senai.hroads.webApi.Domains.ClassesHabilidade", null)
                        .WithMany("ListaClasses")
                        .HasForeignKey("ClassesHabilidadeidClasseHabilidade");
                });

            modelBuilder.Entity("senai.hroads.webApi.Domains.ClassesHabilidade", b =>
                {
                    b.HasOne("senai.hroads.webApi.Domains.Classe", "classe")
                        .WithMany()
                        .HasForeignKey("idClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("senai.hroads.webApi.Domains.Habilidade", "habilidade")
                        .WithMany()
                        .HasForeignKey("idHabilidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("classe");

                    b.Navigation("habilidade");
                });

            modelBuilder.Entity("senai.hroads.webApi.Domains.Habilidade", b =>
                {
                    b.HasOne("senai.hroads.webApi.Domains.ClassesHabilidade", null)
                        .WithMany("ListaHabilidades")
                        .HasForeignKey("ClassesHabilidadeidClasseHabilidade");

                    b.HasOne("senai.hroads.webApi.Domains.TipoHabilidadeDomain", "tipoHabilidade")
                        .WithMany()
                        .HasForeignKey("idTipoHabilidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoHabilidade");
                });

            modelBuilder.Entity("senai.hroads.webApi.Domains.Personagem", b =>
                {
                    b.HasOne("senai.hroads.webApi.Domains.Classe", "classe")
                        .WithMany()
                        .HasForeignKey("idClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("senai.hroads.webApi.Domains.Usuario", "usuario")
                        .WithMany("personagens")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("classe");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("senai.hroads.webApi.Domains.Usuario", b =>
                {
                    b.HasOne("senai.hroads.webApi.Domains.TiposUsuario", "tipoUsuario")
                        .WithMany()
                        .HasForeignKey("idTipoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoUsuario");
                });

            modelBuilder.Entity("senai.hroads.webApi.Domains.ClassesHabilidade", b =>
                {
                    b.Navigation("ListaClasses");

                    b.Navigation("ListaHabilidades");
                });

            modelBuilder.Entity("senai.hroads.webApi.Domains.Usuario", b =>
                {
                    b.Navigation("personagens");
                });
#pragma warning restore 612, 618
        }
    }
}
